services:
  microplus:
    build:
      context: .
      dockerfile: Dockerfile
    image: microplus:latest
    container_name: microplus
    restart: unless-stopped
    ports:
      - "4000:4000"
    env_file:
      - .env.local
    networks:
      - microplus-net

networks:
  microplus-net:
    driver: bridge
